name: GitHub Actions Demo
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore: 
      - .github/**
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.name }}
      - run: echo ${{ github.ref }}
      - run: ls -lsa
  
